seed: 0
device: cuda:0
num_steps_per_env: 24
max_iterations: 3000
empirical_normalization: false
obs_groups:
  policy:
  - policy
  teacher:
  - teacher
clip_actions: null
save_interval: 100
experiment_name: biped
run_name: scan-student-s0
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: true
load_run: 2026-08-21_12-15-46_scan-teacher-s0
load_checkpoint: model_.*.pt
class_name: DistillationRunner
policy:
  class_name: StudentTeacherRecurrent
  init_noise_std: 0.1
  noise_std_type: scalar
  student_obs_normalization: false
  teacher_obs_normalization: false
  student_hidden_dims:
  - 256
  - 128
  - 128
  teacher_hidden_dims:
  - 256
  - 128
  - 128
  activation: elu
  rnn_type: lstm
  rnn_hidden_dim: 256
  rnn_num_layers: 1
  teacher_recurrent: false
algorithm:
  class_name: Distillation
  num_learning_epochs: 1
  learning_rate: 0.001
  gradient_length: 24
  max_grad_norm: 1.0
  optimizer: adam
  loss_type: mse
